"""Add profile page dynamic features (#205)

* Add profile page dynamic features

Signed-off-by: Vihan <contact@vihan.org>

* Add frontend w/ popovers

Signed-off-by: Vihan <contact@vihan.org>

* Modify docs

Signed-off-by: Vihan <contact@vihan.org>

* Fix capitalization because I am genius

Signed-off-by: Vihan <contact@vihan.org>

* Move DB commits to controller

Signed-off-by: Vihan <contact@vihan.org>

Revision ID: 2f545da3d087
Revises: 82017c29712e
Create Date: 2018-07-29 23:27:16.640305+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f545da3d087'
down_revision = '82017c29712e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_following',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('following_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], )
    )
    op.drop_table('post_categories')
    op.add_column('users', sa.Column('following_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'following_public')
    op.create_table('post_categories',
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='post_categories_ibfk_1'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_categories_ibfk_2'),
    sa.PrimaryKeyConstraint('category_id', 'post_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_following')
    # ### end Alembic commands ###
