"""MySQL 8.0 upgrade requirements (merge after upgrade) (#206)

Revision ID: 82017c29712e
Revises: 1f03d42a8eaf
Create Date: 2018-07-29 22:35:43.046189+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82017c29712e'
down_revision = '1f03d42a8eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
